# Generated by Django 5.2.5 on 2025-08-14 11:47

import django.db.models.deletion
from django.db import migrations, models


def create_default_institute(apps, schema_editor):
    """Create a default Institute for existing Department records"""
    Institute = apps.get_model('api', 'Institute')
    default_institute = Institute.objects.create(
        id=1,
        name='Default Institute',
        description='Default institute created during migration'
    )
    return default_institute


def reverse_create_default_institute(apps, schema_editor):
    """Remove the default Institute"""
    Institute = apps.get_model('api', 'Institute')
    Institute.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_teacher_alter_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(
            create_default_institute,
            reverse_create_default_institute,
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.institute'),
            preserve_default=False,
        ),
    ]
