# Generated by Django 5.2.5 on 2025-08-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_institute_semester_department_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studyprogram'),
        ),
    ]
