# Generated by Django 5.2.5 on 2025-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_studyprogram_courses_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, help_text='e.g., S05618', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_format',
            field=models.CharField(blank=True, help_text='e.g., 2025W, 2026S', max_length=10, null=True),
        ),
    ]
