# Generated by Django 5.2.5 on 2025-08-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_course_number_course_semester_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=0)),
                ('semester_number', models.IntegerField(help_text='Which semester this subject is taught in')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='api.studyprogram')),
            ],
        ),
        migrations.CreateModel(
            name='StudySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=0)),
                ('hours_per_week', models.IntegerField(default=0)),
                ('subject_type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('practical', 'Practical'), ('project', 'Project'), ('thesis', 'Thesis')], default='lecture', max_length=50)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_subjects', to='api.curriculumsubject')),
            ],
        ),
    ]
