# Generated by Django 5.2.5 on 2025-08-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_curriculumsubject_studysubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.curriculumsubject'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studysubject'),
        ),
    ]
