# Generated by Django 5.2.5 on 2025-08-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_step2_course_semester_many_to_many'),
    ]

    operations = [
        # Step 1: Update Semester model options and fields
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-year', '-season']},
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='e.g., 2025W, 2026S', max_length=20),
        ),
        
        # Step 2: Add unique constraint (now that duplicates are removed)
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'season')},
        ),
    ]

    dependencies = [
        ('api', '0010_step2_course_semester_many_to_many'),
    ]

    operations = [
    ]
