# Generated by Django 5.2.5 on 2025-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_step3_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-year', '-season']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(blank=True, help_text='Semesters where this course is offered', related_name='courses', to='api.semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='e.g., 2025W, 2026S', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'season')},
        ),
    ]
