# Generated by Django 5.2.5 on 2025-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_semester_options_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code', 'title']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, default=1, help_text='Unique course code, e.g., S05618, S04261', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='api_course_course__aeafd3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year', 'semester_format'], name='api_course_year_2e1f84_idx'),
        ),
    ]
