# Generated by Django 5.2.5 on 2025-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_course_code_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='api_course_year_2e1f84_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_format',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year'], name='api_course_year_96aacb_idx'),
        ),
    ]
